### PR TITLE
Fixes issue preventing installation.

### PR DESCRIPTION
**Pull request by Xliff**
- Adds "resource" section to META6.json
- Minor change to Algorithm::LBFGS::Parameter made to allow code to find
the library built in the distro.

### CODE REVIEW

**Comment by titsuki** [comment]
Thanks for your PR!

But this module doesn't cause any errors on the latest master branch:
https://travis-ci.org/titsuki/p6-Algorithm-LBFGS/builds/406780537

I think I just forgot to bump its version and the CPAN version still falls by the different reason (i.e., https://github.com/titsuki/p6-Algorithm-LBFGS/commit/40a49755d5e2709211f0f87dc3eb4d17c800db77).

**Comment by titsuki** [comment]
Sorry, I found that this module was on ecosystem not CPAN.
Could I see the build log that reports install failure?

**Comment by titsuki** [comment]
@Xliff Thanks for your PR! But AFAIK current build process works fine. So, I'll close this PR. If you still have this problem feel free to reopen this issue.

**Comment by Xliff** [comment]
@titsuki - Anytime! Glad the problem was resolved and all I stumbled across was stale code! ;)

**Pull request closed without merging**
